# SPDX-FileCopyrightText: Copyright (C) 2018-2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
name: action-update
'on':
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  action-update:
    # yamllint disable-line rule:line-length
    uses: fabriciofx/github-workflows/.github/workflows/action-update-template.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
